#!/usr/bin/env bash
TEMPLATE=$(cat template.json)

echo $TEMPLATE > comment.json
echo $TEMPLATE > doctype.json
#echo $TEMPLATE > a.json
echo $TEMPLATE > abbr.json
echo $TEMPLATE > acronym.json
echo $TEMPLATE > address.json
echo $TEMPLATE > applet.json
echo $TEMPLATE > area.json
echo $TEMPLATE > article.json
echo $TEMPLATE > aside.json
echo $TEMPLATE > audio.json
echo $TEMPLATE > b.json
echo $TEMPLATE > base.json
echo $TEMPLATE > basefont.json
echo $TEMPLATE > bdi.json
echo $TEMPLATE > bdo.json
echo $TEMPLATE > big.json
echo $TEMPLATE > blockquote.json
echo $TEMPLATE > body.json
#echo $TEMPLATE > br.json
echo $TEMPLATE > button.json
echo $TEMPLATE > canvas.json
echo $TEMPLATE > caption.json
echo $TEMPLATE > center.json
echo $TEMPLATE > cite.json
echo $TEMPLATE > code.json
echo $TEMPLATE > col.json
echo $TEMPLATE > colgroup.json
echo $TEMPLATE > data.json
echo $TEMPLATE > datalist.json
echo $TEMPLATE > dd.json
echo $TEMPLATE > del.json
echo $TEMPLATE > details.json
echo $TEMPLATE > dfn.json
echo $TEMPLATE > dialog.json
echo $TEMPLATE > dir.json
echo $TEMPLATE > div.json
echo $TEMPLATE > dl.json
echo $TEMPLATE > dt.json
echo $TEMPLATE > em.json
echo $TEMPLATE > embed.json
echo $TEMPLATE > fieldset.json
echo $TEMPLATE > figcaption.json
echo $TEMPLATE > figure.json
echo $TEMPLATE > font.json
echo $TEMPLATE > footer.json
echo $TEMPLATE > form.json
echo $TEMPLATE > frame.json
echo $TEMPLATE > frameset.json
echo $TEMPLATE > h1.json
echo $TEMPLATE > h2.json
echo $TEMPLATE > h3.json
echo $TEMPLATE > h4.json
echo $TEMPLATE > h5.json
echo $TEMPLATE > h6.json
echo $TEMPLATE > head.json
echo $TEMPLATE > header.json
echo $TEMPLATE > hr.json
echo $TEMPLATE > html.json
echo $TEMPLATE > i.json
echo $TEMPLATE > iframe.json
echo $TEMPLATE > img.json
echo $TEMPLATE > input.json
echo $TEMPLATE > ins.json
echo $TEMPLATE > kbd.json
echo $TEMPLATE > label.json
echo $TEMPLATE > legend.json
echo $TEMPLATE > li.json
echo $TEMPLATE > link.json
echo $TEMPLATE > main.json
echo $TEMPLATE > map.json
echo $TEMPLATE > mark.json
echo $TEMPLATE > menu.json
echo $TEMPLATE > menuitem.json
echo $TEMPLATE > meta.json
echo $TEMPLATE > meter.json
echo $TEMPLATE > nav.json
echo $TEMPLATE > noframes.json
echo $TEMPLATE > noscript.json
echo $TEMPLATE > object.json
echo $TEMPLATE > ol.json
echo $TEMPLATE > optgroup.json
echo $TEMPLATE > option.json
echo $TEMPLATE > output.json
echo $TEMPLATE > p.json
echo $TEMPLATE > param.json
echo $TEMPLATE > picture.json
echo $TEMPLATE > pre.json
echo $TEMPLATE > progress.json
echo $TEMPLATE > q.json
echo $TEMPLATE > rp.json
echo $TEMPLATE > rt.json
echo $TEMPLATE > ruby.json
echo $TEMPLATE > s.json
echo $TEMPLATE > samp.json
echo $TEMPLATE > script.json
echo $TEMPLATE > section.json
echo $TEMPLATE > select.json
echo $TEMPLATE > small.json
echo $TEMPLATE > source.json
echo $TEMPLATE > span.json
echo $TEMPLATE > strike.json
echo $TEMPLATE > strong.json
echo $TEMPLATE > style.json
echo $TEMPLATE > sub.json
echo $TEMPLATE > summary.json
echo $TEMPLATE > sup.json
echo $TEMPLATE > table.json
echo $TEMPLATE > tbody.json
echo $TEMPLATE > td.json
echo $TEMPLATE > textarea.json
echo $TEMPLATE > tfoot.json
echo $TEMPLATE > th.json
echo $TEMPLATE > thead.json
echo $TEMPLATE > time.json
echo $TEMPLATE > title.json
echo $TEMPLATE > tr.json
echo $TEMPLATE > track.json
echo $TEMPLATE > tt.json
echo $TEMPLATE > u.json
echo $TEMPLATE > ul.json
echo $TEMPLATE > var.json
echo $TEMPLATE > video.json
echo $TEMPLATE > wbr